### ISSUE TITLE
Handle scientists and engineers

### ISSUE THREAD

**Issue by Xymanek** [robojumper/robojumperSquadSelect#1]
My suggestion: for non-soldiers remove everything except:

- name
- removal button
- stats

Maybe even make some of sort of event so that other mods can modify what panels should be shown for individual units

**Comment by Xymanek** [comment]
You might also want to use the engineering or science icons instead of the class one

**Comment by robojumper** [comment]
Closed in 72b268e49e6ccd3f6a3d50a55c98bb11083b6a06
