### ISSUE TITLE
Add additional information boxes per slot on top of it

### ISSUE THREAD

**Issue by Xymanek** [robojumper/robojumperSquadSelect#2]
And add hook for other mods to configure them. The messages need to show even when slot is empty (on top of giant "select soldier" button)

For example, for WOTCStrategyOverhaul/CovertInfiltration we will need:

- Negates risk: xyz
- Requires class: Reaper

**Comment by robojumper** [comment]
Closed in 29203117e936200c510ba9a4ba22a0417caf21bb
